[project]
name = "comfyui_dynamic"
description = """
Python script executor, powerful control panel (resource monitor, models management), \
pipe any, switch any (branch/if), file reading, diagram display (Graphviz, Mermaid, PlantUML) and other useful tools.\
"""
# 9527
version = "1.3.0"
license = { file = "LICENSE.md" }
dependencies = ["psutil", "pynvml"]
classifiers = ["Operating System :: OS Independent"]

[project.urls]
Repository = "https://github.com/inkbottle-9/comfyui_dynamic"
Documentation = "https://github.com/inkbottle-9/comfyui_dynamic/wiki"
"Bug Tracker" = "https://github.com/inkbottle-9/comfyui_dynamic/issues"

[tool.comfy]
PublisherId = "inkbottle-9"
DisplayName = "Dynamic Python Script Executor (interpreter)"
Icon = "https://raw.githubusercontent.com/inkbottle-9/comfyui_dynamic/refs/heads/main/icon/logo__comfy_dynamic.png"
Banner = "https://raw.githubusercontent.com/inkbottle-9/comfyui_dynamic/refs/heads/main/icon/logo__comfy_dynamic__banner.png"
